#!/bin/bash
##  2018年1月23日 17:14:57
##chenyu
##环境cnetos 6.9
###########################
DNS=`grep 'server' /etc/resolv.conf |awk '{print $2}'`
IP=`ifconfig|grep "Bcast"|awk '{ print $2 }'|awk -F':' '{print $2}'`
NAME=`hostname`
HOST=$1
if [ $# -eq 0 ];then
	echo "enter $0 linux_name"
	exit
fi
##########优化chkconfig
LANG=en_UTF-8
chkconfig|egrep -v "sshd|network|rsyslog|crond|sysstat"|gawk '{print "chkconfig " $1 " off" }'|bash
########################关selinux
sed -i 's#=enforcing#=disabled#g' /etc/selinux/config&&setenforce 0&> /dev/null
######################改名##########
echo  "127.0.0.1 $1 " >>/etc/hosts
sed -i "s/${NAME}/${HOST}/g" /etc/sysconfig/network
echo "---------------------------"
echo "Renamed OK"
echo "---------------------------"
echo "your IP $IP "
echo "---------------------------"
echo  "your linux name $NAME"
echo "---------------------------"
echo  "your linux DNS $DNS"
echo "---------------------------"
